parameters:
    trigger.example.class: JD\TriggerBundle\EventListener\TrackerListener

services:
    trigger.example:
        class: %trigger.example.class%
        tags:
            - { name: kernel.event_listener, event: thing.tracker, method: onThingTracked }

