parameters:
#    pipeline.example.class: JD\PipelineBundle\Example

services:
#    pipeline.example:
#        class: %pipeline.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
